# Generated by Django 3.1.7 on 2021-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qId', models.CharField(max_length=30)),
                ('qText', models.CharField(max_length=50)),
                ('qAnswer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RightQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qId', models.CharField(max_length=30)),
                ('qText', models.CharField(max_length=50)),
                ('qAnswer', models.TextField()),
            ],
        ),
    ]
