# Generated by Django 3.1.7 on 2021-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('addressText1', models.CharField(max_length=50)),
                ('addressText2', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=30)),
                ('supportMail', models.EmailField(max_length=254)),
                ('partnerMail', models.EmailField(max_length=254)),
            ],
        ),
    ]
