# Generated by Django 3.1.7 on 2021-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='productImgs')),
                ('imgTitle', models.CharField(max_length=30)),
                ('imgDesc', models.TextField()),
                ('isVideo', models.BooleanField(default=False)),
                ('videoThumb', models.ImageField(upload_to='productImgs')),
                ('videoId', models.CharField(max_length=30)),
                ('videoTitle', models.CharField(max_length=30)),
                ('videoDesc', models.TextField()),
            ],
        ),
    ]
