# Generated by Django 3.1.7 on 2021-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blogItemPics')),
                ('imgAltText', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=75)),
                ('bodyText', models.TextField()),
            ],
        ),
    ]
