# Generated by Django 3.1.7 on 2021-05-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_photoblogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('thumbImg', models.ImageField(upload_to='blogItemPics')),
                ('thumbImgAltText', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=75)),
                ('bodyText', models.TextField()),
            ],
        ),
    ]
