# Generated by Django 3.1.7 on 2021-05-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_videoblogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblogitem',
            name='headline',
            field=models.TextField(),
        ),
    ]
