# Generated by Django 3.1.7 on 2021-05-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_videoblogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('titleDesc', models.TextField()),
                ('isVideoAvailable', models.BooleanField(default=False)),
                ('videoId', models.CharField(max_length=30)),
                ('thumbImg', models.ImageField(upload_to='blogItemPics')),
                ('thumbImgAltText', models.CharField(max_length=30)),
                ('videoTitle', models.CharField(max_length=100)),
                ('videoDesc', models.TextField()),
                ('startingPrice', models.FloatField(verbose_name=0.0)),
                ('ffFlag', models.BooleanField(default=False)),
                ('ffTitle1', models.TextField()),
                ('ffTitle2', models.TextField()),
                ('ffImg', models.ImageField(upload_to='blogItemPics')),
                ('ffImgAltText', models.CharField(max_length=30)),
                ('ffDesc', models.TextField()),
                ('sfFlag', models.BooleanField(default=False)),
                ('sfTitle1', models.TextField()),
                ('sfTitle2', models.TextField()),
                ('sfImg', models.ImageField(upload_to='blogItemPics')),
                ('sfImgAltText', models.CharField(max_length=30)),
                ('sfDesc', models.TextField()),
                ('tfFlag', models.BooleanField(default=False)),
                ('tfTitle1', models.TextField()),
                ('tfTitle2', models.TextField()),
                ('tfImg', models.ImageField(upload_to='blogItemPics')),
                ('tfImgAltText', models.CharField(max_length=30)),
                ('tfDesc', models.TextField()),
                ('bottomHeadline', models.TextField()),
                ('bottomText', models.TextField()),
            ],
        ),
    ]
