# Generated by Django 3.1.7 on 2021-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_reviewblogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewblogitem',
            name='ffTitle1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewblogitem',
            name='ffTitle2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewblogitem',
            name='sfTitle1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewblogitem',
            name='sfTitle2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewblogitem',
            name='tfTitle1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewblogitem',
            name='tfTitle2',
            field=models.CharField(max_length=30),
        ),
    ]
