# Generated by Django 3.1.7 on 2021-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSelected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=30)),
                ('zipCode', models.IntegerField(default=0)),
            ],
        ),
    ]
