# Generated by Django 3.1.7 on 2021-05-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_deliveryoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSelected', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='paymentCompanyLogos')),
                ('imgTitle', models.CharField(max_length=30)),
                ('imgAltText', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
    ]
