# Generated by Django 3.1.7 on 2021-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210522_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='img',
            field=models.ImageField(upload_to='productImgs'),
        ),
    ]
