# Generated by Django 3.1.7 on 2021-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFavorite', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='productItem')),
                ('imgAltText', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('sale', models.FloatField(default=0.0)),
                ('isOffer', models.BooleanField(default=False)),
                ('priceThrough', models.FloatField(default=0.0)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
    ]
