# Generated by Django 3.1.7 on 2021-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataMarker', models.IntegerField(default=1)),
                ('isActive', models.BooleanField(default=False)),
                ('isVideo', models.BooleanField(default=False)),
                ('videoId', models.CharField(max_length=30)),
                ('videoTitle', models.CharField(max_length=100)),
                ('videoDesc', models.TextField()),
                ('videoThumbImg', models.ImageField(upload_to='productDetailImgs')),
                ('videoThumbImgAltText', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='productDetailImgs')),
                ('imgAltText', models.CharField(max_length=30)),
            ],
        ),
    ]
