# Generated by Django 3.1.7 on 2021-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_previewitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewitem',
            name='img',
            field=models.ImageField(upload_to='productImgs'),
        ),
    ]
