# Generated by Django 3.1.7 on 2021-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cartItemImgs')),
                ('imgAltText', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
