# Generated by Django 3.1.7 on 2021-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerPosition', models.BooleanField(default=False)),
                ('leftPosition', models.BooleanField(default=False)),
                ('rightPosition', models.BooleanField(default=False)),
                ('dataMarker', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=40)),
                ('subTitle', models.TextField()),
                ('imgPrimary', models.ImageField(upload_to='slidePics')),
                ('imgSecondary', models.ImageField(upload_to='slidePics')),
                ('imgAltText', models.CharField(max_length=30)),
            ],
        ),
    ]
